#!/usr/bin/env bash
# Regenerate docs/demo-transcript.txt from a fresh ./scripts/demo.sh run.
# Normalizes machine-specific paths so the transcript is portable and
# reviewable on the GitHub README without leaking local temp paths.
#
# Usage: ./scripts/refresh-transcript.sh
#
# After running, commit docs/demo-transcript.txt.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

OUT="docs/demo-transcript.txt"

# Run the demo and capture raw output, then normalize paths.
{
  echo "<!-- Auto-generated by: ./scripts/refresh-transcript.sh"
  echo "     Source: ./scripts/demo.sh --no-pause"
  echo "     Do not edit by hand — re-run this script to refresh."
  echo "     Machine-specific paths normalized to portable placeholders. -->"
  echo
  ./scripts/demo.sh --no-pause 2>&1
} | /usr/bin/env python3 -c '
import re, sys
src = sys.stdin.read()
# Normalize machine-specific paths
patterns = [
    (r"/Volumes/data/codex-mcp-doctor", "<repo-root>"),
    (r"/home/runner/work/codex-mcp-doctor/codex-mcp-doctor", "<repo-root>"),
    (r"/opt/homebrew/opt/python@3\.\d+/bin/python3[\d.]*", "python3"),
    (r"/opt/homebrew/bin/python3", "python3"),
    (r"/usr/local/bin/python3", "python3"),
    (r"/var/folders/[^\s\)]+\.json\.[A-Za-z0-9]+", "/tmp/baseline.json"),
    (r"/tmp/[^\s\)]+\.json\.[A-Za-z0-9]+", "/tmp/baseline.json"),
    # Strip non-deterministic timing (varies every run) so the transcript
    # only changes when real content changes, not when the machine is faster.
    (r" \(\d+ms\)", ""),
]
for pat, repl in patterns:
    src = re.sub(pat, repl, src)
sys.stdout.write(src)
' > "$OUT"

echo "Wrote $OUT ($(wc -l < "$OUT") lines)"
